import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { data: session } = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {session && (
        <>
          Hello, {session.user?.name}
          <button onClick={() => signOut()}>Sign out</button>
        </>
      )}

      {!session && (
        <>
          Not signed in
          <button onClick={() => signIn("dex")}>Sign in</button>
        </>
      )}
    </div>
  );
}
